version: 2.1

jobs:
  build_linux_image:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin mtools node

      - run:
          name: Prepare the Chroot Environment
          command: |
            debootstrap --arch=amd64 focal ubuntu-chroot http://archive.ubuntu.com/ubuntu/
            mount -t proc /proc ubuntu-chroot/proc
            mount -o bind /dev ubuntu-chroot/dev
            mount -o bind /sys ubuntu-chroot/sys

      - run:
          name: Install Xorg and Minimal Dependencies
          command: |
            chroot ubuntu-chroot /bin/bash -c "apt-get update && apt-get install -y xorg openbox"

      - run:
          name: Download and Set Up Electron AppImage
          command: |
            git clone https://github.com/Qrodex/SkoopinOS
            cd SkoopinOS
            npm install
            npm run build
            chmod +x ubuntu-chroot/root/dist/SkoopinOS.AppImage

      - run:
          name: Configure Autostart
          command: |
            echo '#!/bin/bash' > ubuntu-chroot/etc/init.d/start-electron-app
            echo 'startx /root/SkoopinOS.AppImage -- -nocursor' >> ubuntu-chroot/etc/init.d/start-electron-app
            chmod +x ubuntu-chroot/etc/init.d/start-electron-app
            ln -s /etc/init.d/start-electron-app ubuntu-chroot/etc/rc2.d/S99startelectronapp

      - run:
          name: Create the SquashFS Filesystem and ISO as before
          command: |
            # Follow previous steps to create filesystem.squashfs, then iso

      - store_artifacts:
          path: ubuntu-electron.iso
          destination: ubuntu-electron.iso

  run_virtual_machine:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Start Virtual Machine
          background: true
          command: |
            qemu-system-x86_64 -enable-kvm -m 2048 -cdrom ubuntu-electron.iso -vnc :0 -daemonize
            sleep 10  # Wait for VM to boot

      - run:
          name: Start x11vnc Server
          command: |
            x11vnc -display :0 -rfbport 5900 -bg -forever

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_linux_image
      - run_virtual_machine:
          requires:
            - build_linux_image
          filters:
            branches:
              only: master  # Example: Run on the master branch